# Generated by Django 5.2 on 2025-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_discount_percent_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(max_length=2000),
        ),
    ]
