# Generated by Django 5.2.5 on 2025-08-14 13:40

from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=orders.models.generate_order_number,
                editable=False,
                max_length=40,
                unique=True,
            ),
        ),
    ]
