# Generated by Django 5.2.5 on 2025-08-15 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
