# Generated by Django 5.2.5 on 2025-08-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_payment_method_delete_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for confirmation"),
                    ("preauth", "Pre-authorized"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("error", "Error"),
                    ("input", "Input"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
