# Generated by Django 5.2.1 on 2025-06-05 09:03

import django.core.validators
from django.db import migrations, models

import careers.models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0002_alter_careerapplication_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerapplication",
            name="resume",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    careers.models.validate_pdf,
                ],
            ),
        ),
    ]
