# Generated by Django 5.2 on 2025-05-19 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_address_order_orderitem_paymentmethod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="user",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
