# Generated by Django 5.2.5 on 2025-08-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "is_primary"], name="users_addre_user_id_278a32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "created_at"], name="users_addre_user_id_1e60ff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="uniq_primary_address_per_user",
            ),
        ),
    ]
